### ISSUE TITLE
help with non avm device

### ISSUE THREAD

**Issue by ehabtanta** [DanielAW/libtr064#1]
tnx

**Comment by DanielAW** [comment]
Hi,

its great to see that my code attracts the attention of someone :-)
But I must admit that I abandoned the project a while ago without acutally finishing it. Currently its not possible for me to spend more time in this.
I can just recomend the project which this code is based on: https://bitbucket.org/kbr/fritzconnection

I hope you could reach your goal via the project in the link above.

Sorry

**Comment by ehabtanta** [comment]
thanks for your reply
